apiVersion: apps/v1
kind: Deployment
metadata:
  name: pedantic-orderliness-${ENV}
  namespace: pedantic-orderliness-${ENV}
  labels:
    app: pedantc-orderliness
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pedantic-orderliness
      env: ${ENV}
  template:
    metadata:
      labels:
        app: pedantic-orderliness
        env: ${ENV}
    spec:
      containers:
        - name: pedantic-orderliness
          image: docker.pedanticorderliness.com/pedantic-orderliness:${TAG_NAME}
          ports:
            - containerPort: 8081
          env:
            - name: ENV
              value: ${ENV}
      imagePullSecrets:
        - name: regcred
